export const SEARCH_POST_STARTED = "FETCH_POST_STARTED";
export const FETCH_POSTS_STARTED = "FETCH_POSTS_STARTED";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const SEARCH_POST_SUCCESS = "FETCH_POST_SUCCESS";
export const FETCH_POSTS_FAILED = "FETCH_POST_FAILED";
export const SEARCH_POST_FAILED = "FETCH_POST_FAILED";
